- .circleci/config.yml
- README.md
- sunrise.config.js
- Rename env vars with VUE_APP as prefix to make it work
- Gave names to the artifacts uploaded in CircleCI
> Fix env vars

- README.md
- netlify.toml
Button + instructions on how to deploy. Additionally, forces to set up env vars for project setup.
> Add Netlify button

- .gitignore
- _vscode/settings.json
It belongs to an IDE/editor, it should be in ignore.
> Remove vscode config file and add to ignore

- jest.config.js
- package-lock.json
- package.json
- tests/unit/HelloWorld.spec.js
- yarn.lock
It was having issues to interpret ES6. But it seems it was a dependency issue.
> Fix jest issue with babel

- src/assets/scss/_general.scss
- src/components/Breadcrumb.vue
- src/components/CategoriesMenu.vue
- src/components/ProductList.vue
- tests/unit/specs/components/Breadcrumb.spec.js
- tests/unit/specs/components/CategoriesMenu.spec.js
- tests/unit/specs/components/ProductList.spec.js
- tests/unit/specs/components/ProductThumbnail.spec.js
- Use transitions to fade in/out
- Distinguish between empty and loading states
- Skip apollo calls when requirements are not met
> Improve rendering of products/categories

- tests/unit/specs/store/categories.spec.js
- Removing unnecessary categories in the category tree
- Better naming for categories
> Improve store categories unit test

- src/components/LoginBoxHeader.vue
- src/router.js
Besides what's mentioned in the titile, to achieve this:
- Used authGuard that redirects to "login" if not authenticated.
- Created "meta" attribute `requiresAuth`, which triggers the authGuard.
- Added `logout=true` to current URL to force Vue Router to re-enter all guards.
> Remain on the same page on logout

- README.md
Improve documentation to configure API Client following Merchant Center instead of Admin Center
> Update documentation following the Merchant Center

- src/assets/scss/_input-fields.scss
- src/assets/scss/_signup-box.scss
- src/components/ValidationError.vue
Fixed border styling and margin in inputs and removed letter spacing that was applied on few parts of the form
> Fix border styling in inputs

- src/store/modules/user.js
> Extract customer info fragment to avoid duplication

- package-lock.json
- package.json
- yarn.lock
Now emails with characters such as `+` are accepted.
> Update auth middleware to fix password flow bug

- README.md
> Simplify doc on how to use diff data

- src/components/header/LoginButton.vue
> Fix log in button style for mobile version

- src/assets/scss/_my-account-personal-details.scss
- src/components/useraccount/SidebarMenu.vue
- src/components/useraccount/UserProfile.vue
- src/i18n/de.json
- src/i18n/en.json
Implemented side menu in user account with a sign out and personal details sections.
> My account side menu

- src/components/common/SelectBoxIt.vue
- src/components/productoverview/ProductSortSelector.vue
- Added a label "Sort by" to understand what the select is.
- Fixed bug with SelectBoxIt which didn't refresh on options changed.
- Improved style of sort selector
> Sort style improvements

- src/components/useraccount/MyOrders.vue
- tests/e2e/specs/myOrders_spec.js
- tests/e2e/support/commands.js
- tests/unit/specs/components/userprofile/myOrders.spec.js
Fixed shipment/payment state in My Orders to show in selected language
> Display shipment/payment state in selected language

- .circleci/config.yml
- package-lock.json
- package.json
- src/apollo.js
- src/auth.js
- src/components/common/LineItem.vue
- src/components/header/LoginButton.vue
- src/components/login/LoginForm.vue
- src/components/login/SignUpForm.vue
- src/components/useraccount/SidebarMenu.vue
- src/main.js
- src/mixins/authMixin.js
- tests/e2e/support/test-apollo.js
- yarn.lock
- Update/remove dependencies according to Vue CLI 3.9.2
- Fix errors related to cyclic dependency and order
- Created `authMixin` to avoid duplication of login/logout and to hide complexity.
> Update dependencies to Vue CLI 3.9.2 and fix related issues

- README.md
- babel.config.js
- netlify.toml
- package-lock.json
- package.json
- src/apollo.js
- src/auth.js
- src/components/common/ServerError.vue
- sunrise.config.js
- tests/unit/specs/components/common/ServerError.spec.js
- yarn.lock
- Clean session and retry authentication on 401 and 403, this makes sure that the local storage is not polluted with a different project.
- Added auth scope to the env vars, otherwise it will fail when an additional permission is required.
- Show 400 errors on submitting forms.
> Retry authentication to commercetools on 401/403 error

- src/components/useraccount/SidebarMenu.vue
- src/components/useraccount/changepassword/TabChangePassword.vue
- src/mixins/customerMixin.js
- src/router.js
- tests/e2e/specs/login_spec.js
- tests/e2e/specs/userProfile_spec.js
- tests/e2e/support/commands.js
- tests/unit/specs/components/userprofile/TabChangePassword.spec.js
- Implemented change password functionality
- Also for e2e test I moved `checkCustomerIsLoggedIn` to `commands.js` as it is used now in more than one test
> Change password functionality

- src/components/useraccount/SidebarMenu.vue
- src/components/useraccount/changepassword/TabChangePassword.vue
- src/mixins/customerMixin.js
- src/router.js
- tests/e2e/specs/userProfile_spec.js
Made a few changes based on Laura's review
> New changes for change password functionality

- src/assets/scss/_cart.scss
- src/assets/scss/_pop.scss
- src/components/cartdetail/PageCartDetail.vue
- src/components/header/MiniCart.vue
- src/components/productoverview/ProductList.vue
- src/components/useraccount/myorders/TabOrderList.vue
- src/i18n/de.yaml
- src/i18n/en.yaml
- src/store.js
- tests/e2e/specs/cartDetailPage_spec.js
- tests/e2e/specs/miniCart_spec.js
- tests/e2e/specs/orderList_spec.js
- tests/e2e/specs/pageProductOverview_spec.js
Handle empty results cases by writing that they're empty on the page:
* Empty cart    
* Empty product list
* Empty orders list
> Handle empty results

- src/components/cartdetail/LineItemQuantityForm.vue
- tests/e2e/specs/cartDetailPage_spec.js
**NEW FEATURE:** 
Now when you decrease the quantity of a line item to less than 1, the line item will be removed from cart.
Fixes #108
> Remove line item from cart when quantity is decreased to zero

- src/components/checkout/CartOverview/script.js
- src/components/checkout/CartOverview/template.html
- src/components/common/cartlike/CartLikeContentDetail/script.js
- src/components/common/shared.js
- src/components/productdetail/ProductInfo/script.js
- tests/e2e/specs/locationSelector_spec.js
- tests/e2e/specs/productDetailPage_spec.js
Show correct price in checkout (with cart discount)
Show correct item price (for country)
> Show correct price with discount

- src/components/common/shared.js
- src/components/productoverview/ProductList/script.js
When fetching price the country is optional (there are USD prices without a country). So when United States is selected as country the preferred price would be currency: USD, country: US, when there is no such price then try currency:USD only (graphql already works like this).
> Country is optional in price

- src/App/template.html
- src/components/cartdetail/PageCartDetail/script.js
- src/components/checkout/CartOverview/script.js
- src/components/checkout/StepPlaceOrderForm/script.js
- src/components/common/Breadcrumb/script.js
- src/components/common/shared.js
- src/components/header/CategoriesMenu/script.js
- src/components/header/LocationSelector/script.js
- src/components/header/MiniCart/script.js
- src/components/home/BannerPicture/script.js
- src/components/productdetail/DetailsSection/script.js
- src/components/productdetail/ProductInfo/script.js
- src/components/productoverview/ProductList/script.js
- src/components/root/index.vue
- src/components/root/script.js
- src/components/root/template.html
- src/components/useraccount/myorders/TabOrderDetail/script.js
- src/mixins/cartMixin.js
- src/router.js
- tests/e2e/specs/login_spec.js
currently /product has a version for each language, should be /en/product or /de/product so each url has unique content.
> Put locale in route

- src/components/productdetail/DetailsSection/script.js
- src/components/productdetail/DetailsSection/template.html
- src/components/productdetail/VariantSelector/script.js
- src/components/productdetail/VariantSelector/template.html
- tests/e2e/specs/productDetailPage_spec.js
- tests/unit/specs/components/productdetail/VariantSelector.spec.js
Attribute tag can be found in product type and is a translated version of the tag (like color and size), use the translated attribute instead of the attribute in product (is the key to the attribute and not the translation)
> Show translated data

- src/assets/scss/_megamenu.scss
- src/components/common/shared.js
- src/components/header/CategoriesMenu/script.js
- src/components/header/CategoriesMenu/template.html
- src/components/header/TheHeader/script.js
- src/components/header/TheHeader/template.html
- tests/e2e/specs/categoriesMenu_spec.js
- tests/unit/specs/components/header/CategoriesMenu.spec.js
Categories menu for mobile devices.
> mobile menu

- src/assets/scss/_pagination.scss
- src/assets/scss/_shop-item.scss
> Fix style issues

- src/components/common/shared.js
- src/components/productoverview/ProductList/script.js
> get correct price from api

- src/components/header/LocationSelector/script.js
- src/components/root/script.js
- src/router.js
- tests/e2e/specs/login_spec.js
Country should be part of the route params
> country in route

- src/components/login/LoginForm/script.js
- src/components/productdetail/ProductInfo/script.js
- src/components/productoverview/ProductList/script.js
- src/mixins/authMixin.js
- src/store.js
Show customer group price
Solves [this](https://github.com/commercetools/sunrise-spa/issues/198) issue.
> Show price for customer group

- sunrise.config.js
- tests/e2e/support/test-apollo.js
Use the new api and auth host, addresses [this](https://github.com/commercetools/sunrise-spa/issues/176) issue.
> Update auth and api host

- src/assets/scss/_cart.scss
- src/components/Cart.gql
- src/components/common/cartlike/CartLikeContentDetail/script.js
- src/components/common/cartlike/CartLikeContentDetail/template.html
- src/components/common/cartlike/CartLikePriceDetail/script.js
- src/components/common/cartlike/CartLikePriceDetail/style.css
- src/components/common/cartlike/CartLikePriceDetail/template.html
> Checkout discount 2

- .gitignore
- package.json
- src/assets/scss/_store-location.scss
- src/components/common/InventoryAvailability/index.vue
- src/components/common/InventoryAvailability/script.js
- src/components/common/InventoryAvailability/style.css
- src/components/common/InventoryAvailability/template.html
- src/components/common/ProductThumbnail/script.js
- src/components/common/ProductThumbnail/style.css
- src/components/common/ProductThumbnail/template.html
- src/components/header/TheHeader/script.js
- src/components/header/TheHeader/template.html
- src/components/productdetail/ProductInfo/script.js
- src/components/productdetail/ProductInfo/template.html
- src/components/productoverview/ProductList/script.js
- src/components/stores/PageStoreLocator/i18n.txt
- src/components/stores/PageStoreLocator/index.vue
- src/components/stores/PageStoreLocator/script.js
- src/components/stores/PageStoreLocator/template.html
- src/main.js
- src/router.js
- src/store.js
- yarn.lock
> Implement store locator on development branch

- .gitignore
- src/assets/scss/_store-location.scss
- src/components/common/Breadcrumb/template.html
- src/components/common/SlideDown/style.scss
- src/components/login/PageLogin/style.scss
- src/components/login/PageLogin/template.html
- src/components/login/SignUpForm/template.html
- src/components/productoverview/PageProductOverview/style.scss
- src/components/productoverview/ProductFilter/style.scss
- src/components/productoverview/ProductList/template.html
> Style dave

- src/components/header/TheHeader/i18n.txt
- src/components/header/TheHeader/index.vue
- src/components/header/TheHeader/script.js
- src/components/header/TheHeader/style.css
- src/components/header/TheHeader/template.html
- src/components/productdetail/DetailsSection/script.js
- src/components/productdetail/ProductGallery/script.js
- src/components/productdetail/ProductGallery/template.html
- src/components/productdetail/ProductInfo/script.js
- src/components/productdetail/VariantSelector/script.js
- src/components/productoverview/ProductList/script.js
- src/components/root/script.js
- src/mixins/productMixin.js
> Preview mode

- README.md
> remove netlify

- src/components/header/CategoriesMenu/CategoriesMenu.vue
> fix bug in menu

- src/components/common/shared.js
- tests/e2e/specs/orderDetail_spec.js
- tests/unit/specs/components/common/cartlike/CartLikeContentDetail.spec.js
> correct total price

- package-lock.json
- package.json
- src/components/common/CartLike/CartLikeContentDetail/CartLikeContentDetail.js
- src/components/common/CartLike/CartLikeContentDetail/CartLikeContentDetail.scss
- src/components/common/CartLike/CartLikeContentDetail/CartLikeContentDetail.txt
- src/components/common/CartLike/CartLikeContentDetail/CartLikeContentDetail.vue
- src/components/common/CartLike/CartLikePriceDetail/CartLikePriceDetail.js
- src/components/common/CartLike/CartLikePriceDetail/CartLikePriceDetail.txt
- src/components/common/CartLike/CartLikePriceDetail/CartLikePriceDetail.vue
- src/components/common/CartLike/CartLikePriceDetail/style.css
- src/components/common/CartLike/CartLikeSummary/CartLikeSummary.js
- src/components/common/CartLike/CartLikeSummary/CartLikeSummary.txt
- src/components/common/CartLike/CartLikeSummary/CartLikeSummary.vue
- src/components/common/CartLike/DiscountCodes/DiscountCodes.js
- src/components/common/CartLike/DiscountCodes/DiscountCodes.txt
- src/components/common/CartLike/DiscountCodes/DiscountCodes.vue
- src/components/common/CartLike/DiscountCodes/style.css
- src/components/common/CartLike/LineItemInfo/LineItemInfo.js
- src/components/common/CartLike/LineItemInfo/LineItemInfo.scss
- src/components/common/CartLike/LineItemInfo/LineItemInfo.txt
- src/components/common/CartLike/LineItemInfo/LineItemInfo.vue
- src/components/common/CartLike/RemoveDiscountCodeForm/RemoveDiscountCodeForm.js
- src/components/common/CartLike/RemoveDiscountCodeForm/RemoveDiscountCodeForm.vue
- tests/e2e/specs/checkoutPage_spec.js
- tests/e2e/specs/miniCart_spec.js
- tests/unit/specs/components/common/ProductThumbnail.spec.js
- tests/unit/specs/components/common/form/ServerError.spec.js
- yarn.lock
Fixed problems with building and testing (see the one todo as providing a different address with checkout is broken)
> Return tab fix

- .eslintrc.js
- package-lock.json
- src/components/cartdetail/LineItemQuantityForm/LineItemQuantityForm.js
- src/components/checkout/BillingDetails/BillingDetails.vue
- src/components/common/CartLike/CartLikeContentDetail/CartLikeContentDetail.js
- src/components/common/CartLike/CartLikeContentDetail/CartLikeContentDetail.scss
- src/components/common/CartLike/CartLikeContentDetail/CartLikeContentDetail.txt
- src/components/common/CartLike/CartLikeContentDetail/CartLikeContentDetail.vue
- src/components/common/CartLike/CartLikePriceDetail/CartLikePriceDetail.js
- src/components/common/CartLike/CartLikePriceDetail/CartLikePriceDetail.txt
- src/components/common/CartLike/CartLikePriceDetail/CartLikePriceDetail.vue
- src/components/common/CartLike/CartLikePriceDetail/style.css
- src/components/common/CartLike/CartLikeSummary/CartLikeSummary.js
- src/components/common/CartLike/CartLikeSummary/CartLikeSummary.txt
- src/components/common/CartLike/CartLikeSummary/CartLikeSummary.vue
- src/components/common/CartLike/DiscountCodes/DiscountCodes.js
- src/components/common/CartLike/DiscountCodes/DiscountCodes.txt
- src/components/common/CartLike/DiscountCodes/DiscountCodes.vue
- src/components/common/CartLike/DiscountCodes/style.css
- src/components/common/CartLike/LineItemInfo/LineItemInfo.js
- src/components/common/CartLike/LineItemInfo/LineItemInfo.scss
- src/components/common/CartLike/LineItemInfo/LineItemInfo.txt
- src/components/common/CartLike/LineItemInfo/LineItemInfo.vue
- src/components/common/CartLike/RemoveDiscountCodeForm/RemoveDiscountCodeForm.js
- src/components/common/CartLike/RemoveDiscountCodeForm/RemoveDiscountCodeForm.vue
- tests/e2e/specs/miniCart_spec.js
- tests/unit/specs/components/common/ProductThumbnail.spec.js
- tests/unit/specs/components/common/form/ServerError.spec.js
> Suggest changes

- src/components/common/CartLike/LineItemInfo/LineItemInfo.vue
- src/components/common/cartlike/LineItemInfo/LineItemInfo.vue
- src/components/useraccount/TabOrderDetail/TabOrderDetail.vue
- src/components/useraccount/TabReturn/TabReturn.js
- src/components/useraccount/TabReturn/TabReturn.scss
- src/components/useraccount/TabReturn/TabReturn.txt
- src/components/useraccount/TabReturn/TabReturn.vue
- tests/e2e/specs/login_spec.js
- tests/e2e/specs/orderDetail_spec.js
> Return items

- src/components/productoverview/ProductList/ProductList.vue
> fix toggle filter (again)!

- Docs/Readme.md
Documentation can be finished when new reset password is implemented (document in that branch and merge there).
> Documentation

- Docs/Readme.md
> documentation update

- .gitignore
- Deploy/Readme.md
- Deploy/main.tf
- Deploy/variables.tf
Deploy using terraform variables.
> Update deploy using vars.

- .eslintrc.js
- .lintgql.js
- package.json
- src/components/checkout/PaymentMethod/Adyen/Adyen.js
- src/components/checkout/ShippingMethod/ShippingMethod.js
- src/components/header/CategoriesMenu/manyCategories/ManyCategories.js
- src/components/header/TheHeader/TheHeader.js
> fixed linting gql queries

- tests/e2e/specs/pageStoreLocator_spec.js
> When run US Berlin matches to something in the US

- src/components/common/BaseAddress/BaseAddress.vue
- tests/e2e/specs/orderDetail_spec.js
test so it doesn't break later
> fix change in address (depricated fields)

- graphql.schema.json
- src/components/productdetail/AddToCartForm/AddToCartForm.js
- src/components/productdetail/AddToCartForm/AddToCartForm.txt
- src/components/productdetail/AddToCartForm/AddToCartForm.vue
- src/components/productdetail/ProductInfo/ProductInfo.txt
- src/components/productdetail/ProductInfo/ProductInfo.vue
> error on maximum quantity

- src/api/api.js
- src/components/common/shared.js
- src/components/productdetail/DetailsSection/DetailsSection.js
- src/components/productdetail/ProductGallery/ProductGallery.js
- src/components/productdetail/ProductGallery/ProductGallery.vue
- src/components/productdetail/ProductInfo/ProductInfo.vue
- src/components/productdetail/VariantSelector/VariantSelector.js
- src/components/productoverview/ProductQuickView/ProductQuickView.js
- src/components/productoverview/ProductQuickView/ProductQuickView.vue
- src/composition/useProductQuery.js
- sunrise.config.js
- tests/e2e/specs/productDetailPage_spec.js
- tests/e2e/support/mutations.js
- tests/unit/specs/components/productdetail/DetailsSection.spec.js
- tests/unit/specs/components/productdetail/ProductGallery.spec.js
- tests/unit/specs/components/productdetail/VariantSelector.spec.js
Using product-projection instead of product so api key does not need "view_product" scope
> Product projection

- src/composition/useProductQuery.js
If there is no channel but availability info from stock entry then use that.
> Availability optionally depends on channel

- sunrise.config.js
Modified sunrise config to use an api key that will enable returning items
> change api-key so can return item(s)

- sunrise.config.js
> publish changes

- .gitignore
- composition/ct/useCartMutation.js
- composition/useAccessRules.js
- composition/useCartMutation.js
- src/presentation/fashion/Header/Header.vue
- src/presentation/fashion/PageCheckout/OrderOverview/OrderOverview.js
- src/presentation/fashion/PageCheckout/OrderOverview/OrderOverview.vue
- src/presentation/fashion/PageCheckout/OrderOverview/PaymentMethod/PaymentMethod.js
- src/presentation/fashion/PageCheckout/OrderOverview/PaymentMethod/PaymentMethod.vue
- src/presentation/fashion/PageCheckout/PageCheckout.js
- src/presentation/fashion/PageCheckout/PageCheckout.vue
Create payment method for order (if scope allows it)
> payment method item for order

- composition/ct/useCustomerTools.js
- composition/ct/useProducts.js
- composition/useCustomerTools.js
- src/presentation/fashion/User/TabDashboard/TabDashboard.js
get custom customer data (for example loyalty points)
> refresh customer info

- composition/useSearch.js
- src/presentation/fashion/Header/Header.js
> fix search
